#ifndef __OP_x86_header__
#define __OP_x86_header__
#define opNameList(opName) \
opName(AAA) \
opName(AAD) \
opName(AAM) \
opName(AAS) \
opName(ADC) \
opName(ADD) \
opName(ADDPD) \
opName(ADDPS) \
opName(ADDSD) \
opName(ADDSS) \
opName(ADDSUBPD) \
opName(ADDSUBPS) \
opName(ADX) \
opName(ALTER) \
opName(AMX) \
opName(AND) \
opName(ANDNPD) \
opName(ANDNPS) \
opName(ANDPD) \
opName(ANDPS) \
opName(ARPL) \
opName(BOUND) \
opName(BSF) \
opName(BSR) \
opName(BSWAP) \
opName(BT) \
opName(BTC) \
opName(BTR) \
opName(BTS) \
opName(CALL) \
opName(CALLF) \
opName(CBW) \
opName(CDQ) \
opName(CDQE) \
opName(CLC) \
opName(CLD) \
opName(CLFLUSH) \
opName(CLI) \
opName(CLTS) \
opName(CMC) \
opName(CMOVA) \
opName(CMOVAE) \
opName(CMOVB) \
opName(CMOVBE) \
opName(CMOVC) \
opName(CMOVE) \
opName(CMOVG) \
opName(CMOVGE) \
opName(CMOVL) \
opName(CMOVLE) \
opName(CMOVNA) \
opName(CMOVNAE) \
opName(CMOVNB) \
opName(CMOVNBE) \
opName(CMOVNC) \
opName(CMOVNE) \
opName(CMOVNG) \
opName(CMOVNGE) \
opName(CMOVNL) \
opName(CMOVNLE) \
opName(CMOVNO) \
opName(CMOVNP) \
opName(CMOVNS) \
opName(CMOVNZ) \
opName(CMOVO) \
opName(CMOVP) \
opName(CMOVPE) \
opName(CMOVPO) \
opName(CMOVS) \
opName(CMOVZ) \
opName(CMP) \
opName(CMPPD) \
opName(CMPPS) \
opName(CMPS) \
opName(CMPSB) \
opName(CMPSD) \
opName(CMPSQ) \
opName(CMPSS) \
opName(CMPSW) \
opName(CMPXCHG) \
opName(CMPXCHG16B) \
opName(CMPXCHG8B) \
opName(COMISD) \
opName(COMISS) \
opName(CPUID) \
opName(CQO) \
opName(CS) \
opName(CVTDQ2PD) \
opName(CVTDQ2PS) \
opName(CVTPD2DQ) \
opName(CVTPD2PI) \
opName(CVTPD2PS) \
opName(CVTPI2PD) \
opName(CVTPI2PS) \
opName(CVTPS2DQ) \
opName(CVTPS2PD) \
opName(CVTPS2PI) \
opName(CVTSD2SI) \
opName(CVTSD2SS) \
opName(CVTSI2SD) \
opName(CVTSI2SS) \
opName(CVTSS2SD) \
opName(CVTSS2SI) \
opName(CVTTPD2DQ) \
opName(CVTTPD2PI) \
opName(CVTTPS2DQ) \
opName(CVTTPS2PI) \
opName(CVTTSD2SI) \
opName(CVTTSS2SI) \
opName(CWD) \
opName(CWDE) \
opName(DAA) \
opName(DAS) \
opName(DEC) \
opName(DIV) \
opName(DIVPD) \
opName(DIVPS) \
opName(DIVSD) \
opName(DIVSS) \
opName(DS) \
opName(EMMS) \
opName(ENTER) \
opName(ES) \
opName(F2XM1) \
opName(FABS) \
opName(FADD) \
opName(FADDP) \
opName(FBLD) \
opName(FBSTP) \
opName(FCHS) \
opName(FCLEX) \
opName(FCMOVB) \
opName(FCMOVBE) \
opName(FCMOVE) \
opName(FCMOVNB) \
opName(FCMOVNBE) \
opName(FCMOVNE) \
opName(FCMOVNU) \
opName(FCMOVU) \
opName(FCOM) \
opName(FCOM2) \
opName(FCOMI) \
opName(FCOMIP) \
opName(FCOMP) \
opName(FCOMP3) \
opName(FCOMP5) \
opName(FCOMPP) \
opName(FCOS) \
opName(FDECSTP) \
opName(FDIV) \
opName(FDIVP) \
opName(FDIVR) \
opName(FDIVRP) \
opName(FFREE) \
opName(FFREEP) \
opName(FIADD) \
opName(FICOM) \
opName(FICOMP) \
opName(FIDIV) \
opName(FIDIVR) \
opName(FILD) \
opName(FIMUL) \
opName(FINCSTP) \
opName(FINIT) \
opName(FIST) \
opName(FISTP) \
opName(FISTTP) \
opName(FISUB) \
opName(FISUBR) \
opName(FLD) \
opName(FLD1) \
opName(FLDCW) \
opName(FLDENV) \
opName(FLDL2E) \
opName(FLDL2T) \
opName(FLDLG2) \
opName(FLDLN2) \
opName(FLDPI) \
opName(FLDZ) \
opName(FMUL) \
opName(FMULP) \
opName(FNCLEX) \
opName(FNINIT) \
opName(FNOP) \
opName(FNSAVE) \
opName(FNSTCW) \
opName(FNSTENV) \
opName(FNSTSW) \
opName(FPATAN) \
opName(FPREM) \
opName(FPREM1) \
opName(FPTAN) \
opName(FRNDINT) \
opName(FRSTOR) \
opName(FS) \
opName(FSAVE) \
opName(FSCALE) \
opName(FSIN) \
opName(FSINCOS) \
opName(FSQRT) \
opName(FST) \
opName(FSTCW) \
opName(FSTENV) \
opName(FSTP) \
opName(FSTP1) \
opName(FSTP8) \
opName(FSTP9) \
opName(FSTSW) \
opName(FSUB) \
opName(FSUBP) \
opName(FSUBR) \
opName(FSUBRP) \
opName(FTST) \
opName(FUCOM) \
opName(FUCOMI) \
opName(FUCOMIP) \
opName(FUCOMP) \
opName(FUCOMPP) \
opName(FWAIT) \
opName(FXAM) \
opName(FXCH) \
opName(FXCH4) \
opName(FXCH7) \
opName(FXRSTOR) \
opName(FXSAVE) \
opName(FXTRACT) \
opName(FYL2X) \
opName(FYL2XP1) \
opName(GS) \
opName(HADDPD) \
opName(HADDPS) \
opName(HLT) \
opName(HSUBPD) \
opName(HSUBPS) \
opName(ICEBP) \
opName(IDIV) \
opName(IMUL) \
opName(IN) \
opName(INC) \
opName(INS) \
opName(INSB) \
opName(INSD) \
opName(INSW) \
opName(INT) \
opName(INT1) \
opName(INTO) \
opName(INVD) \
opName(INVLPG) \
opName(IRET) \
opName(IRETD) \
opName(IRETQ) \
opName(JA) \
opName(JAE) \
opName(JB) \
opName(JBE) \
opName(JC) \
opName(JCXZ) \
opName(JE) \
opName(JECXZ) \
opName(JG) \
opName(JGE) \
opName(JL) \
opName(JLE) \
opName(JMP) \
opName(JMPF) \
opName(JNA) \
opName(JNAE) \
opName(JNB) \
opName(JNBE) \
opName(JNC) \
opName(JNE) \
opName(JNG) \
opName(JNGE) \
opName(JNL) \
opName(JNLE) \
opName(JNO) \
opName(JNP) \
opName(JNS) \
opName(JNZ) \
opName(JO) \
opName(JP) \
opName(JPE) \
opName(JPO) \
opName(JRCXZ) \
opName(JS) \
opName(JZ) \
opName(LAHF) \
opName(LAR) \
opName(LDDQU) \
opName(LDMXCSR) \
opName(LDS) \
opName(LEA) \
opName(LEAVE) \
opName(LES) \
opName(LFENCE) \
opName(LFS) \
opName(LGDT) \
opName(LGS) \
opName(LIDT) \
opName(LLDT) \
opName(LMSW) \
opName(LOCK) \
opName(LODS) \
opName(LODSB) \
opName(LODSD) \
opName(LODSQ) \
opName(LODSW) \
opName(LOOP) \
opName(LOOPE) \
opName(LOOPNE) \
opName(LOOPNZ) \
opName(LOOPZ) \
opName(LSL) \
opName(LSS) \
opName(LTR) \
opName(MASKMOVDQU) \
opName(MASKMOVQ) \
opName(MAXPD) \
opName(MAXPS) \
opName(MAXSD) \
opName(MAXSS) \
opName(MFENCE) \
opName(MINPD) \
opName(MINPS) \
opName(MINSD) \
opName(MINSS) \
opName(MONITOR) \
opName(MOV) \
opName(MOVAPD) \
opName(MOVAPS) \
opName(MOVD) \
opName(MOVDDUP) \
opName(MOVDQ2Q) \
opName(MOVDQA) \
opName(MOVDQU) \
opName(MOVHLPS) \
opName(MOVHPD) \
opName(MOVHPS) \
opName(MOVLHPS) \
opName(MOVLPD) \
opName(MOVLPS) \
opName(MOVMSKPD) \
opName(MOVMSKPS) \
opName(MOVNTDQ) \
opName(MOVNTI) \
opName(MOVNTPD) \
opName(MOVNTPS) \
opName(MOVNTQ) \
opName(MOVQ) \
opName(MOVQ2DQ) \
opName(MOVS) \
opName(MOVSB) \
opName(MOVSD) \
opName(MOVSHDUP) \
opName(MOVSLDUP) \
opName(MOVSQ) \
opName(MOVSS) \
opName(MOVSW) \
opName(MOVSX) \
opName(MOVSXD) \
opName(MOVUPD) \
opName(MOVUPS) \
opName(MOVZX) \
opName(MUL) \
opName(MULPD) \
opName(MULPS) \
opName(MULSD) \
opName(MULSS) \
opName(MWAIT) \
opName(NEG) \
opName(nop) \
opName(NOP) \
opName(NOT) \
opName(NTAKEN) \
opName(OR) \
opName(ORPD) \
opName(ORPS) \
opName(OUT) \
opName(OUTS) \
opName(OUTSB) \
opName(OUTSD) \
opName(OUTSW) \
opName(PABSB) \
opName(PABSD) \
opName(PABSW) \
opName(PACKSSDW) \
opName(PACKSSWB) \
opName(PACKUSWB) \
opName(PADDB) \
opName(PADDD) \
opName(PADDQ) \
opName(PADDSB) \
opName(PADDSW) \
opName(PADDUSB) \
opName(PADDUSW) \
opName(PADDW) \
opName(PALIGNR) \
opName(PAND) \
opName(PANDN) \
opName(PAUSE) \
opName(PAVGB) \
opName(PAVGW) \
opName(PCMPEQB) \
opName(PCMPEQD) \
opName(PCMPEQW) \
opName(PCMPGTB) \
opName(PCMPGTD) \
opName(PCMPGTW) \
opName(PEXTRW) \
opName(PHADDD) \
opName(PHADDSW) \
opName(PHADDW) \
opName(PHSUBD) \
opName(PHSUBSW) \
opName(PHSUBW) \
opName(PINSRW) \
opName(PMADDUBSW) \
opName(PMADDWD) \
opName(PMAXSW) \
opName(PMAXUB) \
opName(PMINSW) \
opName(PMINUB) \
opName(PMOVMSKB) \
opName(PMULHRSW) \
opName(PMULHUW) \
opName(PMULHW) \
opName(PMULLW) \
opName(PMULUDQ) \
opName(POP) \
opName(POPA) \
opName(POPAD) \
opName(POPF) \
opName(POPFD) \
opName(POPFQ) \
opName(POR) \
opName(PREFETCHNTA) \
opName(PREFETCHT0) \
opName(PREFETCHT1) \
opName(PREFETCHT2) \
opName(PSADBW) \
opName(PSHUFB) \
opName(PSHUFD) \
opName(PSHUFHW) \
opName(PSHUFLW) \
opName(PSHUFW) \
opName(PSIGNB) \
opName(PSIGND) \
opName(PSIGNW) \
opName(PSLLD) \
opName(PSLLDQ) \
opName(PSLLQ) \
opName(PSLLW) \
opName(PSRAD) \
opName(PSRAW) \
opName(PSRLD) \
opName(PSRLDQ) \
opName(PSRLQ) \
opName(PSRLW) \
opName(PSUBB) \
opName(PSUBD) \
opName(PSUBQ) \
opName(PSUBSB) \
opName(PSUBSW) \
opName(PSUBUSB) \
opName(PSUBUSW) \
opName(PSUBW) \
opName(PUNPCKHBW) \
opName(PUNPCKHDQ) \
opName(PUNPCKHQDQ) \
opName(PUNPCKHWD) \
opName(PUNPCKLBW) \
opName(PUNPCKLDQ) \
opName(PUNPCKLQDQ) \
opName(PUNPCKLWD) \
opName(PUSH) \
opName(PUSHA) \
opName(PUSHAD) \
opName(PUSHF) \
opName(PUSHFD) \
opName(PUSHFQ) \
opName(PXOR) \
opName(RCL) \
opName(RCPPS) \
opName(RCPSS) \
opName(RCR) \
opName(RDMSR) \
opName(RDPMC) \
opName(RDTSC) \
opName(REP) \
opName(REPE) \
opName(REPNE) \
opName(REPNZ) \
opName(REPZ) \
opName(RETF) \
opName(RETN) \
opName(REX) \
opName(REXoB) \
opName(REXoR) \
opName(REXoRB) \
opName(REXoRX) \
opName(REXoRXB) \
opName(REXoW) \
opName(REXoWB) \
opName(REXoWR) \
opName(REXoWRB) \
opName(REXoWRX) \
opName(REXoWRXB) \
opName(REXoWX) \
opName(REXoWXB) \
opName(REXoX) \
opName(REXoXB) \
opName(ROL) \
opName(ROR) \
opName(RSM) \
opName(RSQRTPS) \
opName(RSQRTSS) \
opName(SAHF) \
opName(SAL) \
opName(SALC) \
opName(SAR) \
opName(SBB) \
opName(SCAS) \
opName(SCASB) \
opName(SCASD) \
opName(SCASQ) \
opName(SCASW) \
opName(SETA) \
opName(SETAE) \
opName(SETALC) \
opName(SETB) \
opName(SETBE) \
opName(SETC) \
opName(SETE) \
opName(SETG) \
opName(SETGE) \
opName(SETL) \
opName(SETLE) \
opName(SETNA) \
opName(SETNAE) \
opName(SETNB) \
opName(SETNBE) \
opName(SETNC) \
opName(SETNE) \
opName(SETNG) \
opName(SETNGE) \
opName(SETNL) \
opName(SETNLE) \
opName(SETNO) \
opName(SETNP) \
opName(SETNS) \
opName(SETNZ) \
opName(SETO) \
opName(SETP) \
opName(SETPE) \
opName(SETPO) \
opName(SETS) \
opName(SETZ) \
opName(SFENCE) \
opName(SGDT) \
opName(SHL) \
opName(SHLD) \
opName(SHR) \
opName(SHRD) \
opName(SHUFPD) \
opName(SHUFPS) \
opName(SIDT) \
opName(SLDT) \
opName(SMSW) \
opName(SQRTPD) \
opName(SQRTPS) \
opName(SQRTSD) \
opName(SQRTSS) \
opName(SS) \
opName(STC) \
opName(STD) \
opName(STI) \
opName(STMXCSR) \
opName(STOS) \
opName(STOSB) \
opName(STOSD) \
opName(STOSQ) \
opName(STOSW) \
opName(STR) \
opName(SUB) \
opName(SUBPD) \
opName(SUBPS) \
opName(SUBSD) \
opName(SUBSS) \
opName(SWAPGS) \
opName(SYSCALL) \
opName(SYSENTER) \
opName(SYSEXIT) \
opName(SYSRET) \
opName(TAKEN) \
opName(TEST) \
opName(UCOMISD) \
opName(UCOMISS) \
opName(UD) \
opName(UD2) \
opName(UNPCKHPD) \
opName(UNPCKHPS) \
opName(UNPCKLPD) \
opName(UNPCKLPS) \
opName(VERR) \
opName(VERW) \
opName(WAIT) \
opName(WBINVD) \
opName(WRMSR) \
opName(XADD) \
opName(XCHG) \
opName(XLAT) \
opName(XLATB) \
opName(XOR) \
opName(XORPD) \
opName(XORPS) \

#endif
